import { DEFAULT_ITEMS } from "../lib/inventory/svg";

const sqlEscape = (s: string) => s.replace(/'/g, "''");

const lines = [
  "-- Auto-generated by scripts/genseed.ts. Re-run: bun run scripts/genseed.ts > supabase/seed.sql",
  "",
  "delete from public.inventory_items where source = 'default' and organisation_id is null;",
  "",
];
for (const it of DEFAULT_ITEMS) {
  lines.push(
    `insert into public.inventory_items (organisation_id, source, name, category, width_mm, depth_mm, height_mm, svg_markup) values (null, 'default', '${sqlEscape(
      it.name,
    )}', '${it.category}', ${it.width_mm}, ${it.depth_mm}, ${it.height_mm}, '${sqlEscape(it.svg)}');`,
  );
}
process.stdout.write(lines.join("\n") + "\n");
